default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5

  host: localhost
  username: mattstjernholm
  password: <%= ENV['MATTSTJERNHOLM_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: mattstjernholm_development
  username: mattstjernholm
  password: <%= ENV['MATTSTJERNHOLM_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: mattstjernholm_test
  username: mattstjernholm
  password: <%= ENV['MATTSTJERNHOLM_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: mattstjernholm_production
  username: mattstjernholm
  password: <%= ENV['MATTSTJERNHOLM_DATABASE_PASSWORD'] %>
